const nodemailer = require("nodemailer");

let transporter = null;

/**
 * Lazy-initialize nodemailer transporter
 */
const getTransporter = () => {
  if (!transporter) {
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      throw new Error("EMAIL_USER and EMAIL_PASS must be configured in environment variables.");
    }

    transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
      pool: true,
      maxConnections: 5,
    });
  }
  return transporter;
};

/**
 * Convert a markdown summary to clean HTML email
 * @param {string} markdown
 * @returns {string} HTML string
 */
const markdownToEmailHtml = (markdown) => {
  let html = markdown
    // Headers
    .replace(/^#{1}\s+(.+)$/gm, "<h1>$1</h1>")
    .replace(/^#{2}\s+(.+)$/gm, "<h2>$1</h2>")
    .replace(/^#{3}\s+(.+)$/gm, "<h3>$1</h3>")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    // Italic
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Bullet points → list items  
    .replace(/^\s*[-*]\s+(.+)$/gm, "<li>$1</li>")
    // Numbered lists
    .replace(/^\d+\.\s+(.+)$/gm, "<li>$1</li>")
    // Paragraph breaks
    .replace(/\n\n/g, "</p><p>")
    // Wrap li items in ul
    .replace(/(<li>[\s\S]*?<\/li>)/g, "<ul>$1</ul>")
    // Line breaks
    .replace(/\n/g, "<br/>");

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Sales Insight Report</title>
      <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6fa; margin: 0; padding: 0; }
        .container { max-width: 700px; margin: 30px auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 40px 40px 30px; color: white; }
        .header h1 { margin: 0; font-size: 26px; font-weight: 700; letter-spacing: -0.5px; }
        .header p { margin: 8px 0 0; opacity: 0.85; font-size: 14px; }
        .badge { display: inline-block; background: rgba(255,255,255,0.2); border-radius: 20px; padding: 4px 14px; font-size: 12px; margin-top: 12px; }
        .content { padding: 36px 40px; color: #333; line-height: 1.7; }
        h1, h2, h3 { color: #4c3d8f; margin-top: 24px; margin-bottom: 8px; }
        h2 { font-size: 18px; border-bottom: 2px solid #f0eeff; padding-bottom: 6px; }
        ul { padding-left: 20px; }
        li { margin-bottom: 6px; }
        strong { color: #2d2d2d; }
        .footer { background: #f8f8fc; padding: 20px 40px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eeeeee; }
        .footer a { color: #667eea; text-decoration: none; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>📊 Sales Insight Report</h1>
          <p>AI-Generated Executive Summary</p>
          <span class="badge">Powered by Google Gemini</span>
        </div>
        <div class="content">
          <p>${html}</p>
        </div>
        <div class="footer">
          <p>This report was automatically generated by <strong>Sales Insight Automator</strong></p>
          <p>Generated on ${new Date().toUTCString()}</p>
        </div>
      </div>
    </body>
    </html>
  `;
};

/**
 * Send an AI-generated sales summary to the recipient email
 * @param {string} toEmail - Recipient email address
 * @param {string} summary - Markdown summary from AI
 * @param {string} senderName - Name of the user who triggered the report
 * @returns {Promise<void>}
 */
const sendSummaryEmail = async (toEmail, summary, senderName = "Sales Insight Automator") => {
  const transport = getTransporter();

  const htmlBody = markdownToEmailHtml(summary);

  const mailOptions = {
    from: `"${senderName}" <${process.env.EMAIL_USER}>`,
    to: toEmail,
    subject: `📊 AI Sales Insight Report — ${new Date().toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    })}`,
    text: `Sales Insight Report\n\n${summary}\n\nGenerated by Sales Insight Automator`,
    html: htmlBody,
  };

  const info = await transport.sendMail(mailOptions);
  return info;
};

module.exports = { sendSummaryEmail };
